


CREATE TABLE IF NOT EXISTS users(
    id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email  TEXT   NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL ,
    createAt  INTEGER NOT NULL DEFAULT 0
)


